CREATE TABLE locations (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL
);

CREATE TABLE users (
    id UUID PRIMARY KEY,
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    location_id INT REFERENCES locations(id) ON DELETE SET NULL,
    birth_date DATE NOT NULL,
    phone VARCHAR(20) UNIQUE,
    email VARCHAR(255) UNIQUE NOT NULL,
    gender VARCHAR(10) CHECK (gender IN ('M', 'F')) NOT NULL
);
